#!/usr/bin/env python3
"""Build worker.js: a Cloudflare Worker serving the review dashboard.

Inputs:
  dashboard.html    - the dashboard page (committed; contains no secrets,
                      fetches aggregated JSON from the Worker's /data endpoint)
  worker_parser.js  - CSV parse/aggregate functions used server-side
  sheet_url.txt     - the private Google Sheet CSV URL (gitignored!)

The sheet URL and raw CSV never reach the browser: /data returns only
[source, sentiment-bucket, agent, location, date] tuples
(/data?v=2 gives "YYYY-MM-DD"; the legacy /data gives "YYYY-MM"), with CORS open so
the GitHub Pages copy of the dashboard can read it too.

Run:  python3 build_worker.py   ->  writes worker.js
"""
from pathlib import Path

HERE = Path(__file__).parent
sheet_url = (HERE / "sheet_url.txt").read_text().strip()
parser_js = (HERE / "worker_parser.js").read_text()
html = (HERE / "dashboard.html").read_text()

assert "docs.google.com" not in html, "dashboard.html must not contain the sheet URL"

# Escape for embedding in a JS template literal.
page = html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

worker = f"""// Cloudflare Worker: Drivo OTA review dashboard.
// Serves the dashboard at "/" and aggregated counts at "/data".
// GENERATED by build_worker.py - do not edit directly.
const SHEET_CSV = {sheet_url!r};
const DATA_TTL_SECONDS = 300; // re-pull the sheet at most every 5 minutes

const UNASSIGNED = "(Unassigned)";
const MONTH_NUM = {{ JANUARY:1, FEBRUARY:2, MARCH:3, APRIL:4, MAY:5, JUNE:6, JULY:7, AUGUST:8, SEPTEMBER:9, OCTOBER:10, NOVEMBER:11, DECEMBER:12 }};

{parser_js}
const CORS = {{ "access-control-allow-origin": "*" }};

async function dataResponse(ctx, version) {{
  const cache = caches.default;
  const cacheKey = new Request("https://internal-cache/data-" + version);
  const hit = await cache.match(cacheKey);
  if (hit) return hit;
  const upstream = await fetch(SHEET_CSV, {{ cf: {{ cacheTtl: 0 }} }});
  if (!upstream.ok) {{
    return new Response(JSON.stringify({{ error: "upstream " + upstream.status }}), {{
      status: 502, headers: {{ "content-type": "application/json", ...CORS }},
    }});
  }}
  let rows = buildRows(await upstream.text());
  // v1 (legacy pages): month keys "YYYY-MM". v2: full dates "YYYY-MM-DD".
  if (version === "v1") rows = rows.map(r => [r[0], r[1], r[2], r[3], r[4].slice(0, 7)]);
  const res = new Response(JSON.stringify({{ rows, fetchedAt: new Date().toISOString() }}), {{
    headers: {{
      "content-type": "application/json",
      "cache-control": "public, max-age=" + DATA_TTL_SECONDS,
      "x-robots-tag": "noindex",
      ...CORS,
    }},
  }});
  ctx.waitUntil(cache.put(cacheKey, res.clone()));
  return res;
}}

const PAGE = `{page}`;

export default {{
  async fetch(request, env, ctx) {{
    const url = new URL(request.url);
    if (url.pathname === "/data") return dataResponse(ctx, url.searchParams.get("v") === "2" ? "v2" : "v1");
    if (url.pathname !== "/") return new Response("Not found", {{ status: 404 }});
    return new Response(PAGE, {{
      headers: {{
        "content-type": "text/html; charset=utf-8",
        "x-robots-tag": "noindex",
        "referrer-policy": "no-referrer",
      }},
    }});
  }},
}};
"""

(HERE / "worker.js").write_text(worker)
print(f"worker.js written ({len(worker):,} bytes); sheet URL embedded server-side only")
